[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000
fs_permissions = [
    { access = "read", path = "lib/foundry-chainlink-toolkit/out" },
]
solc_version = "0.8.20"
# Remappings in remappings.txt

# See more config options https://github.com/gakonst/foundry/tree/master/config
